# Template PHP Build

# This template allows you to validate your PHP application.
# The workflow allows running tests and code linting on the default branch.

image: composer:2.0

pipelines:
  pull-requests:
    '{feature/*,bugfix/*}':
      - parallel:
        - step:
            name: Tests
            script:
              - composer update --no-plugins --no-scripts
              - cp .env.example .env
              - composer dumpautoload
              - php vendor/bin/phpunit --log-junit ./tests/test-reports/junit.xml
        - step:
            name: CodeSniffer
            script:
              - composer update --no-plugins --no-scripts
              - apk update && apk add --no-cache git
              - cp .env.example .env
              - composer dumpautoload
              - php vendor/bin/phpcs $(git diff --name-only --diff-filter=d origin/develop)
  branches:
    develop:
      - step:
          name: 'Deployment to Staging'
          image: kroniak/ssh-client
          deployment: staging
          script:
            - echo "Starting deployment to staging..."
            - ssh ${SSH_USER}@${SSH_ADDRESS} -p ${SSH_PORT} 'cd ~/homologa; git pull origin develop; php artisan migrate; php artisan cache:clear'
    main:
      - step:
          name: 'Deployment to Production'
          image: kroniak/ssh-client
          deployment: production
          script:
            - echo "Starting deployment to production..."
            - ssh ${SSH_USER}@${SSH_ADDRESS} -p ${SSH_PORT} 'cd ~/ambientalis; git pull origin main;'

options:
  docker: true